//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRChatUtilModule.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRChatUtilModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Display name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Account_Display_Name {
            get {
                return ResourceManager.GetString("Account_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friends に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Account_Friends {
            get {
                return ResourceManager.GetString("Account_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Account_Mail_Address {
            get {
                return ResourceManager.GetString("Account_Mail_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Account_User_Name {
            get {
                return ResourceManager.GetString("Account_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Downloading {
            get {
                return ResourceManager.GetString("Data_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friends に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HamburgerMenu_Friends {
            get {
                return ResourceManager.GetString("HamburgerMenu_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HamburgerMenu_Message {
            get {
                return ResourceManager.GetString("HamburgerMenu_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HamburgerMenu_SearchUser {
            get {
                return ResourceManager.GetString("HamburgerMenu_SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Worlds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HamburgerMenu_SearchWorld {
            get {
                return ResourceManager.GetString("HamburgerMenu_SearchWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HamburgerMenu_Settings {
            get {
                return ResourceManager.GetString("HamburgerMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HamburgerMenu_User {
            get {
                return ResourceManager.GetString("HamburgerMenu_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_Option {
            get {
                return ResourceManager.GetString("Search_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter　 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_Option_Filter {
            get {
                return ResourceManager.GetString("Search_Option_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort　 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_Option_Sort {
            get {
                return ResourceManager.GetString("Search_Option_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_Option_Sort_Option {
            get {
                return ResourceManager.GetString("Search_Option_Sort_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_Option_User_Name {
            get {
                return ResourceManager.GetString("Search_Option_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   World name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_Option_Word_Name {
            get {
                return ResourceManager.GetString("Search_Option_Word_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   World group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search_Option_World_Group {
            get {
                return ResourceManager.GetString("Search_Option_World_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avatar publish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string System_Avatar_Access {
            get {
                return ResourceManager.GetString("System_Avatar_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allowed to publish avatar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string System_Avatar_Access_Allow {
            get {
                return ResourceManager.GetString("System_Avatar_Access_Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Denied to publish avatar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string System_Avatar_Access_Deny {
            get {
                return ResourceManager.GetString("System_Avatar_Access_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   World publish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string System_World_Access {
            get {
                return ResourceManager.GetString("System_World_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allowed to publish worlds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string System_World_Access_Allow {
            get {
                return ResourceManager.GetString("System_World_Access_Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Denied to publish worlds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string System_World_Access_Deny {
            get {
                return ResourceManager.GetString("System_World_Access_Deny", resourceCulture);
            }
        }
    }
}
